name: twogo_planning
resolution: workspace
publish_to: none
description: 2GO Travel Planning Module
version: 1.0.0

environment:
  sdk: '^3.8.0'
  flutter: '>=3.32.0'

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  app_roteiros_api: any
  equatable: any
  twogo_core: any
  twogo_design_system: any
  twogo_networking: any
  twogo_places: any
  twogo_security: any
  twogo_storage: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences: ^2.5.2
